package control;

public enum Actions {

	ADD_REGISTRY_BUTTON, ACCEPT_FORMULARY_BUTTON, CANCEL_FORMULARY_BUTTON,REPORT_BUTTON,
	REMOVE_REGISTRY_BUTTON, BARS_REPORT_BUTTON, LINEAL_REPORT_BUTTON, X_BOX_DIVISIONS, Y_BOX_DIVISIONS,
	SAVE_BUTTON,LOAD_BUTTON, EXPAND_BUTTON_UP, EXPAND_BUTTON_DOWN, OK_BUTTON_ALERT, EXPAND_BUTTON_UP_REPORT;
	
}
